# Generated by Django 3.0 on 2024-01-25 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_auto_20240125_1547'),
        ('hotel_room', '0002_auto_20240125_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=20, unique=True)),
                ('booking_status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked-in', 'Checked-in'), ('checked-out', 'Checked-out'), ('canceled', 'Canceled'), ('abandoned', 'Abandoned')], max_length=50)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.Person')),
                ('rooms', models.ManyToManyField(related_name='rooms', to='hotel_room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, default=datetime.date(2024, 1, 25), null=True)),
                ('check_out', models.DateField(blank=True, default=datetime.date(2024, 1, 25), null=True)),
                ('room_cleaning', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='user_profile.Person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotel_room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, default=datetime.date(2024, 1, 25), null=True)),
                ('check_out', models.DateField(blank=True, default=datetime.date(2024, 1, 25), null=True)),
                ('room_cleaning', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0)),
                ('new_field', models.CharField(default='SOME STRING', max_length=140)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.Person')),
                ('reservation_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_booking.Booking')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_room.Room')),
            ],
        ),
    ]
