# Generated by Django 3.2 on 2022-10-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('style', models.CharField(choices=[('standard', 'Standard'), ('delux', 'Delux'), ('family', 'Family Suite'), ('business', 'Business Suite')], max_length=20)),
                ('booking_price', models.IntegerField()),
                ('is_smoking', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_room.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateTimeField()),
                ('duration_in_days', models.SmallIntegerField()),
                ('booking_status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked-in', 'Checked-in'), ('checked-out', 'Checked-out'), ('canceled', 'Canceled'), ('abandoned', 'Abandoned')], max_length=50)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_room.room')),
            ],
        ),
    ]
